### ISSUE TITLE
[PE-D] Command "help delete" output is not in the united form 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T13-1/tp#138]
Command inputted: `help delete`

The `PATIENT_ID` format should have square brackets (`[PATIENT_ID]`) to be uniform with the rest of the `help` commands

![image.png](https://raw.githubusercontent.com/datn02/ped/main/files/43640765-e7b4-4320-b699-59efcbc0a34d.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: datn02/ped#2

**Comment by Kureans** [comment]
Patient_ID here does not have square brackets around it to indicate that it is a mandatory field, which is in line with other commands that have mandatory fields like find, etc

**Comment by jushg** [comment]
Write in the UG, update general help function to say mandatory or optional.
