### ISSUE TITLE
[PE-D] Find Command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T13-1/tp#140]
Since it is possible to leave some cells as blank, I was hoping that I could use the find command to get all the cells which are empty. For example, ‘find n/’ could return all the rows which have empty names. I believe the team used the .contains() method for this, hence this result. Can consider implementing an edge case for this feature.

![Error 10.png](https://raw.githubusercontent.com/DJ-Tan/ped/main/files/852feece-f824-4b0b-8777-968a77c2e8d2.png)

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: DJ-Tan/ped#9

**Comment by jushg** [comment]
Return all empty field
