### ISSUE TITLE
[PE-D] Add commands permits the use of no specifier and accepts invalid IC input

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T13-1/tp#148]
Command inputted: `add A-123456EW n/ Dan p/ 12345678 e/ something@example.com a/ 3`

With no `[i/PATIENT_ID]` or `[i/PATIENT_IC]` specifier, also the NRIC has a non-alphanumeric character in it, the add command still accepted this as a valid input.
The list result shows patient with empty IC number.

![image.png](https://raw.githubusercontent.com/datn02/ped/main/files/04c0ce18-e560-4c96-b529-db9bd3b87862.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: datn02/ped#5

**Comment by Kureans** [comment]
issue with bug rpt, wrong input
