### ISSUE TITLE
[PE-D] Crash when writing to unprivileged space

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113-T13-1/tp#153]
When running app from System32 (which requires admin permission), file is unable to be created. Hence when listing patients, the app will crash. 

May want to consider throwing an exception if cannot write to path

![image.png](https://raw.githubusercontent.com/wutdequack/ped/main/files/b3509a81-d676-4e9e-bdc5-21549b95dc63.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: wutdequack/ped#2

**Comment by jushg** [comment]
Handle exception "cant save"
